import type { NextPage } from 'next'
import Head from 'next/head';
import CallToContact from '../components/CallToContact';
import Greeting from '../components/Greeting';
import NavigationBar from '../components/NavigationBar';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className={styles.header}>
          <NavigationBar />
          <Greeting />
        </header>

        <section className={styles.description}>
          Hi, I’ m Ivan, a Brazilian software engineer specializing on
          fault-tolerant applications and Distributed Systems. Well-versed in numerous
          technologies including Node.js, Go, React, Graphql, Docker,
          Kubernetes and AWS.
        </section>

        <CallToContact />
      </main>
    </div>
  )
}

export default Home
